test_bcast: $(test_bcast.o)
	$(link-target)

test_send_recv: $(test_send_recv.o)
	$(link-target)

test_comm_split: $(test_comm_split.o)
	$(link-target)

test_reduce: $(test_reduce.o)
	$(link-target)

test_allreduce: $(test_allreduce.o)
	$(link-target)

test_gather: $(test_gather.o)
	$(link-target)

test_allgather: $(test_allgather.o)
	$(link-target)

test_gatherv: $(test_gatherv.o)
	$(link-target)

test_scatter: $(test_scatter.o)
	$(link-target)
