.SECONDEXPANSION:

test_allgather.o: $$(_modobj_libmpifx_module)
test_allgather.o = test_allgather.o $($(_modobj_libmpifx_module))

test_gather.o: $$(_modobj_libmpifx_module)
test_gather.o = test_gather.o $($(_modobj_libmpifx_module))

test_gatherv.o: $$(_modobj_libmpifx_module)
test_gatherv.o = test_gatherv.o $($(_modobj_libmpifx_module))

test_send_recv.o: $$(_modobj_libmpifx_module)
test_send_recv.o = test_send_recv.o $($(_modobj_libmpifx_module))

test_bcast.o: $$(_modobj_libmpifx_module)
test_bcast.o = test_bcast.o $($(_modobj_libmpifx_module))

test_scatter.o: $$(_modobj_libmpifx_module)
test_scatter.o = test_scatter.o $($(_modobj_libmpifx_module))

test_comm_split.o: $$(_modobj_libmpifx_module)
test_comm_split.o = test_comm_split.o $($(_modobj_libmpifx_module))

test_reduce.o: $$(_modobj_libmpifx_module)
test_reduce.o = test_reduce.o $($(_modobj_libmpifx_module))

test_allreduce.o: $$(_modobj_libmpifx_module)
test_allreduce.o = test_allreduce.o $($(_modobj_libmpifx_module))

