###############################################################################
#
# Library makefile
#
# Needs following variables:
#     FXX: Fortran 2003 compiler
#     FXXOPT: Options for the Fortran 2003 compiler
#     M4: M4 macro processor
#     M4OPT: Options for the M4 macro processor. You should use the -I option
#         with this directory, if you are invoking the makefile from somewhere
#         else. You may also use the -D option to define macros (e.g. DEBUG)
#
###############################################################################

.SUFFIXES:
.SUFFIXES: .f90 .F90 .o

TARGETLIB = libmpifx.a

.PHONY: all
all: $(TARGETLIB)

include Makefile.dep

$(TARGETLIB): $(libmpifx.o)
	ar r $@ $^

%.f90: %.F90
	$(M4) $(M4OPT) $< > $@

%.o: %.f90
	$(FXX) $(FXXOPT) -c $<


.PHONY: clean realclean
clean:
	rm -f *.o

distclean: clean
	rm -f *.mod
	rm -f $(TARGETLIB)


### Local Variables:
### mode:makefile
### End:
