###############################################################################
#
# Library makefile
#
# Needs following variables:
#     FXX: Fortran 2003 compiler
#     FXXOPT: Options for the Fortran 2003 compiler
#     FYPP: FYPP pre-processor
#     FYPPOPT: Options for the FYPP pre-processor. You should use the -I option
#         with this directory, if you are invoking the makefile from somewhere
#         else. You may also use the -D option to define macros (e.g. DEBUG)
#
###############################################################################

.SUFFIXES:
.SUFFIXES: .f90 .fpp .o

TARGETLIB = libmpifx.a

.PHONY: all
all: $(TARGETLIB)

include Makefile.dep

$(TARGETLIB): $(module.o)
	ar r $@ $^

%.f90: %.fpp
	$(FYPP) $(FYPPOPT) $< > $@

%.o: %.f90
	$(FXX) $(FXXOPT) -c $<


.PHONY: clean realclean
clean:
	rm -f *.o

distclean: clean
	rm -f *.mod
	rm -f $(TARGETLIB)


### Local Variables:
### mode:makefile
### End:
